name: Continuos Integration & Continuous Deployment workflow

on: [ push, pull_request ]

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install NPM dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Run tests
        run: npm test
  deploy_to_staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    needs: [ lint_and_test ]
    if: github.ref == refs/heads/develop
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_STAGING }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to heroku
        run: heroku container:login
      - name: Build and push
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME_STAGING }} web
      - name: Release
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME_STAGING }} web
  deploy_to_production:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: [ lint_and_test ]
    if: github.ref == refs/heads/master
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to heroku
        run: heroku container:login
      - name: Build and push
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
      - name: Release
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
